### ISSUE TITLE
Temperature chunk issue

### ISSUE THREAD

**Issue by Creutzx** [rmichie/StatusAndTrendsRMarkdown#59]
https://github.com/rmichie/StatusAndTrendsRMarkdown/blob/3af900ada686d4702007558a6a52831ee728bd1a/Output_Report.Rmd#L1280

![image](https://user-images.githubusercontent.com/32490475/50025582-e3ff3580-ff9a-11e8-977d-5e412270416e.png)

This Area has 8 sites for temperature trend analysis, but I only get through 3 of them before I get this error. Past experience suggested to me that this was related to NAs in the data frame, but I wasn't able to locate them. Ideas?

**Comment by donco** [comment]
I'll take a look, which area are you working in?

**Comment by Creutzx** [comment]
North and Middle Forks John Day. If it helps, I can bring it up on my machine...

**Comment by donco** [comment]
Give it a try now. It was an issue with the temperature plotting function where the function thought it was supposed to be plotting a spawning criteria line, but none of the samples were taken during the spawning season.

**Comment by donco** [comment]
Make sure to reload your functions scripts...
