### ISSUE TITLE
Need to incorporate changes from aaee507 into Exec_Summary_Child.Rmd

### ISSUE THREAD

**Issue by rmichie** [rmichie/StatusAndTrendsRMarkdown#60]
When we made the switch to AWQMS there were changes to the executive summary (commit aaee507) that did not make it into Exec_Summary_Child.Rmd. Those changes need to be incorporated.

**Comment by donco** [comment]
I've recreated the enhancement branch, updated the language, aligned with the current master, and created a pull request for review.

**Comment by rmichie** [comment]
Closed. Addressed in 315cc84.
