### ISSUE TITLE
Temperature chunk

### ISSUE THREAD

**Issue by Creutzx** [rmichie/StatusAndTrendsRMarkdown#65]
https://github.com/rmichie/StatusAndTrendsRMarkdown/blob/62d7f9140d7fde47577f2d9d3b1975ba7baec490/Output_Report.Rmd#L1228

I've been trying to figure out this temperature issue... The number of stations w/ sufficient data for status & trend analysis table lists 24 and 13 stations, respectively. Thirteen graphs are produced, but no table. Any ideas?

![image](https://user-images.githubusercontent.com/32490475/50364744-3229b100-0526-11e9-9ab2-9930372427d4.png)

**Comment by donco** [comment]
Yeah, the plotting function is trying to get the data together for the trend line without checking if there should be a trend line first. I wrapped it in a trend_logic check in the last report I made. You can see it in the fun.plots plot.temperature code here: https://github.com/rmichie/StatusAndTrendsRMarkdown/commit/3ef32b50c0ebeaa8bdfe69221e716addf9eece49

I will make a new branch and add this fix but it will require Ryan to approve it so you may want to manually add it to your fun.plots now.

**Comment by Creutzx** [comment]
Thanks, I'll give that a try.

**Comment by donco** [comment]
Fixed in [#76](https://github.com/rmichie/StatusAndTrendsRMarkdown/pull/76)
