### ISSUE TITLE
Exceedance reporting for TP and TSS

### ISSUE THREAD

**Issue by rmichie** [rmichie/StatusAndTrendsRMarkdown#68]
Right now ‘0’ is reported for number of exceedances of Total Phosphorus and TSS when there isn’t a TMDL target.  Should this say ’N/A’ instead?

**Comment by donco** [comment]
Addressed in [#78](https://github.com/rmichie/StatusAndTrendsRMarkdown/pull/78)

**Comment by rmichie** [comment]
If there is no TMDL target "NA" is reported in the TP and TSS exceedance tables. Issue closed.
