### ISSUE TITLE
Executive Summary - Change Column Names for Table 3, Table 4

### ISSUE THREAD

**Issue by BTDangelo** [rmichie/StatusAndTrendsRMarkdown#70]
The Exec_Summary_Child.Rmd file was outputting a different Summary in Tables 3 and 4 than the summary in Table 15. The order of column names in the Executive Summary does not align with the Output_Report and needs to be changed to this (lines 81-88 of Exec_Summary_Child):

 colnames(stns_param_summary_tbl) <- c("Station ID", "Station Description",
                                                                  "DO Status", "DO Trend",
                                                                  "_E. coli_  Status", "_E. coli_ Trend", 
                                                                  "_Enterococcus_ Status", "_Enterococcus_ Trend",
                                                                  "pH Status", "pH Trend", 
                                                                  "Temperature Status", "Temperature Trend",
                                                                  "TP Status","TP Trend", 
                                                                   "TSS Status","TSS Trend")

**Comment by rmichie** [comment]
Closing. Addressed in 7871ebe.
