### ISSUE TITLE
Auto Conclusions

### ISSUE THREAD

**Issue by BTDangelo** [rmichie/StatusAndTrendsRMarkdown#71]
Currently the auto conclusions (Output Report lines 1720- 1736, Exec Summary lines 168 - 184)  are referencing **stns_param_summary**, causing the auto conclusions to be shifted. If the _colnames_ and _conclusions.parameter_ reference **stns_param_summary_tbl** instead, then the auto conclusions are correct.

**Comment by rmichie** [comment]
Closing. Addressed in 7871eb.
